driver:
  package: romea_gps_driver
  executable: serial_node
  # plugin: romea::ros2::GpsSerialDriver
  # component_container: perception_container
  parameters:
    frame_id: gps_link
    device: "/dev/ttyACM0"
    baudrate: 115200
    rate: 10
ntrip:
  package: ntrip_client
  executable: ntrip_ros.py
  parameters:
    host: caster.centipede.fr
    port: 2101
    username: centipede
    password: centipede
    mountpoint: MTLDR
    authenticate: true
  remappings:
    nmea: ntrip/nmea
    rtcm: ntrip/rtcm
