driver:
  package: romea_gps_driver
  executable: tcp_client_node
  plugin: romea::ros2::GpsTcpDriver
  parameters:
    frame_id: gps_link
    ip: 192.168.0.50
    nmea_port: 1001
    rtcm_port: 1002
    rate: 10
ntrip:
  package: ntrip_client
  executable: ntrip_ros.py
  plugin: none
  parameters:
    host: caster.centipede.fr
    port: 2101
    username: centipede
    password: centipede
    mountpoint: MTLDR
    authenticate: true
  remappings:
    nmea: ntrip/nmea
    rtcm: ntrip/rtcm
