# nmea_driver:
#   package: nmea_navsat_driver
#   executable: nmea_topic_serial_reader
#   parameters:
#     frame_id:
#       source:
#         from: gps_configuration
#         parameter: frame_id
#     port:
#       source:
#         from: gps_driver_configuration
#         parameter: nmea_driver.parameters.port
#     baud:
#       source:
#         from: gps_driver_configuration
#         parameter: nmea_driver.parameters.baud
#   remappings:
#     nmea_sentence: nmea
# topic_driver:
#   package: nmea_navsat_driver
#   executable: nmea_topic_driver
#   remappings:
#     nmea_sentence: nmea
