nmea_driver:
  package: nmea_navsat_driver
  executable: nmea_topic_serial_reader
  parameters:
    frame_id:
      from: gps_configuration
      remap: frame_id
    port:
      from: gps_driver_configuration
    baud:
      from: gps_driver_configuration
  remappings:
    nmea_sentence: nmea
topic_driver:
  package: nmea_navsat_driver
  executable: nmea_topic_driver
  remappings:
    nmea_sentence: nmea
