ntrip:
  package: ntrip_client
  executable: ntrip_ros.py
  parameters:
    host:
      source:
        from: ntrip_driver_configuration
        parameter: ntrip.parameters.host
      default: caster.centipede.fr
    port: 2101
    username:
      source:
        from: ntrip_driver_configuration
        parameter: ntrip.parameters.username
      default: centipede
    password:
      source:
        from: ntrip_driver_configuration
        parameter: ntrip.parameters.password
      default: centipede
    mountpoint:
      source:
        from: ntrip_driver_configuration
        parameter: ntrip.parameters.mountpoint
    authenticate:
      source:
        from: ntrip_driver_configuration
        parameter: ntrip.parameters.authenticate
      default: true
  remappings:
    nmea: ntrip/nmea
    rtcm: ntrip/rtcm
