pkg: ntrip_client
exec: ntrip_ros.py
name: ntrip_client
param:
  - name: host
    value:
      source:
        from: node_configuration
        param: host
      default: caster.centipede.fr
  - name: port
    value: 2101
  - name: username
    value:
      source:
        from: node_configuration
        param: username
      default: centipede
  - name: password
    value:
      source:
        from: node_configuration
        param: password
      default: centipede
  - name: mountpoint
    value:
      source:
        from: node_configuration
        param: mountpoint
  - name: authenticate
    value:
      source:
        from: node_configuration
        param: authenticate
      default: true
remap:
  - from: nmea
    to: ntrip/nmea
  - from: rtcm
    to: ntrip/rtcm
