driver:
  package: romea_gps_driver
  executable: tcp_client_node
  plugin: romea::ros2::GpsTcpDriver
  parameters:
    frame_id:
      from: gps_configuration
      remap: frame_id
    rate:
      from: gps_configuration
      remap: rate
    ip:
      from: driver_configuration
    nmea_port:
      from: driver_configuration
    rtcm_port:
      from: driver_configuration
ntrip:
  package: ntrip_client
  executable: ntrip_ros.py
  plugin: none
  parameters:
    host:
      from: driver_configuration
      default: caster.centipede.fr
    port: 2101
    username:
      from: driver_configuration
      default: centipede
    password:
      from: driver_configuration
      default: centipede
    mountpoint:
      from: driver_configuration
    authenticate:
      from: driver_configuration
      default: true
  remappings:
    nmea: ntrip/nmea
    rtcm: ntrip/rtcm
