pkg: romea_gps_driver
exec: serial_node
plugin: romea::ros2::GpsSerialDriver
name: driver
param:
  - name: frame_id
    value:
      source:
        from: gps_configuration
        param: frame_id
  - name: rate
    value:
      source:
        from: gps_configuration
        param: rate
  - name: device
    value:
      source:
        from: node_configuration
        param: device
  - name: baudrate
    value:
      source:
        from: node_configuration
        param: baudrate
