driver:
  package: romea_gps_driver
  executable: tcp_client_node
  plugin: romea::ros2::GpsTcpDriver
  component_container:
    from: gps_driver_configuration
    default: null
  parameters:
    frame_id:
      from: gps_configuration
      remap: frame_id
    rate:
      from: gps_configuration
      remap: rate
    ip:
      from: gps_driver_configuration
    nmea_port:
      from: gps_driver_configuration
    rtcm_port:
      from: gps_driver_configuration
