driver:
  package: romea_gps_driver
  executable: tcp_client_node
  plugin: romea::ros2::GpsTcpDriver
  component_container:
    from: gps_driver_configuration
    default: null
  parameters:
    frame_id:
      source:
        from: gps_configuration
        parameter: frame_id
    rate:
      source:
        from: gps_configuration
        parameter: rate
    ip:
      source:
        from: gps_driver_configuration
        parameter: driver.parameters.ip
    nmea_port:
      source:
        from: gps_driver_configuration
        parameter: driver.parameters.nmea_port
    rtcm_port:
      source:
        from: gps_driver_configuration
        parameter: driver.parameters.rtcm_port
