driver:
  package: romea_gps_driver
  executable: serial_node
  plugin: romea::ros2::GpsSerialDriver
  component_container:
    from: gps_driver_configuration
    default: null
  parameters:
    frame_id:
      from: gps_configuration
      name: frame_id
    rate:
      from: gps_configuration
      name: rate
    device:
      from: gps_driver_configuration
    baudrate:
      from: gps_driver_configuration
