driver:
  package: romea_gps_driver
  executable: serial_node
  plugin: romea::ros2::GpsSerialDriver
  component_container:
    from: gps_driver_configuration
    default: null
  parameters:
    frame_id:
      source:
        from: gps_configuration
        parameter: frame_id
    rate:
      source:
        from: gps_configuration
        parameter: rate
    device:
      source:
        from: gps_driver_configuration
        parameter: driver.parameters.device
    baudrate:
      source:
        from: gps_driver_configuration
        parameter: driver.parameters.baudrate
